### ISSUE TITLE
Make this package releasable on npmjs.com

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/LifToken#318]
We should be going for a releasable repository. In this issue I'd like to list and complete all the necessary things that have to be done before the first release is possible. The final product of this issue should be a versioned package on npm.

**TODO**

- [x] Cleanup stale branches if there are any
- [x] Enforce node version with `.nvm` file - https://github.com/creationix/nvm - #323
- [x] Enforce node version with `engine` field in `package.json` - https://docs.npmjs.com/files/package.json#engines - #323
- [x] Contribution guidelines - #322 
- [x] Up to date documentation in code
- [x] The build for npmjs should contain compiled ABI interfaces that are required in JS world. - #324

I think these are the minimal steps for the first release. It si then possible to vastly improve the release process with:

- Releases done by CI server triggered by pushing to a specific branch. I'm not sure if we can do this with current CI setup. It is also possible to set this up firstly without semantic-release, just to do it in an iterative way.
- http://commitizen.github.io/cz-cli/ - Uniform commit messages
- https://semantic-release.gitbooks.io/semantic-release/#highlights - Release building automation based on commit messages, however it does not seem to seamlessly support the pre-production 0.* releases. If we are not afraid of many breaking versions, we might want to start at 1.0.0. Also this requires `node 8.3`.
- https://github.com/conventional-changelog/conventional-github-releaser - Automatically created github releases

**Comment by JirkaChadima** [comment]
I think that after merging #323 and #324, this is ready to be closed

**Comment by JirkaChadima** [comment]
We are there! https://www.npmjs.com/package/@windingtree/lif-token

**Comment by czervenka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Alpha version](https://trello.com/c/Wnt7Wg64/8-release-alpha-version)

**Comment by czervenka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Alpha version](https://trello.com/c/Wnt7Wg64/8-release-alpha-version)
