### ISSUE TITLE
Make this package releasable on ethpm.com

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/LifToken#319]
We should be going for a releasable repository. In this issue I'd like to list and complete all the necessary things that have to be done before the first release is possible. The final product of this issue should be a versioned package on ethpm. Publishing to ethpm should be part of the same process that does #318

**TODO**

- [ ] Cleanup stale branches if there are any
- [ ] Contribution guidelines - https://github.com/blog/1184-contributing-guidelines
- [ ] Up to date documentation in code

The deployed package should contain smart contract source codes.
