### ISSUE TITLE
lif1: finalisation of token

### ISSUE THREAD

**Issue by mfw78** [windingtree/LifToken#342]
**Overview**

Lif1 token to be deprecated in favour of lif2.

**Tasks**

- [x] #343

Deploy smart contract to handle:
  - [ ] Pausing of Lif1: `pause()`.
  - [ ] Undo pausing: `undo()`.
  - [ ] Finalize (callable after `period` of 12 months): `finalize()`.
  
Suggested that as part of the L2 migration process, administration control of `LifToken` be passed to a standalone contract that implements the above methods, with `pause()` and `undo()` permissioned (callable only by the community multi-sig), and `finalize()` callable by any party after `period` to permanently set the `owner` to `address(0)`, renouncing all control over Lif1 permanently.
